Add helm chart description to README
scalar-labs/scalar-admin-for-kubernetes pull request #31
Opened 2024-03-11 09:27 UTC by kota2and3kan

## Description

This PR adds the description of Helm Chart for `Scalar Admin for Kubernetes`.

Please take a look!

## Related issues and/or PRs

N/A

## Changes made

* Update README.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

2024-03-12 02:04 UTC, josh-wong requested changes
I've added one suggestion with a couple questions. PTAL!

2024-03-12 02:51 UTC, kota2and3kan commented on README.md
> +You can use Helm Chart to deploy Scalar Admin for Kubernetes in the Kubernetes environment. See [Configure a custom values file for ScalarDB Cluster](https://scalardb.scalar-labs.com/docs/latest/helm
@josh-wong 
Thank you for your review!

> - How about if we combine the two sentences into one sentence?

Looks good! Thank you for your suggestion!

> - Do we need to include links to any other docs for configuring custom values files?
>   - For example, we have other docs that describe how to configure a custom values file listed at [Configure a custom values file for Scalar Helm Charts](https://scalardb.scalar-labs.com/docs/latest/helm-charts/configure-custom-values-file/). If so, I think we'll need to reword this a bit more.

Ah, sorry... I set the wrong document link...
For Scalar Admin for Kubernetes, users only need to see the following two documents.

1. [Configure a custom values file for Scalar Admin for Kubernetes](https://scalardb.scalar-labs.com/docs/latest/helm-charts/configure-custom-values-scalar-admin-for-kubernetes/)
1. [How to deploy Scalar Admin for Kubernetes](https://scalardb.scalar-labs.com/docs/latest/helm-charts/how-to-deploy-scalar-admin-for-kubernetes/)

And, basically, they don't need to update other custom values files like ScalarDB Cluster or ScalarDL to run Scalar Admin for Kubernetes.

So, how about the following sentence?

```suggestion
For details on how to use a Helm Chart to deploy Scalar Admin for Kubernetes in a Kubernetes environment, see:

1. [Configure a custom values file for Scalar Admin for Kubernetes](https://scalardb.scalar-labs.com/docs/latest/helm-charts/configure-custom-values-scalar-admin-for-kubernetes/)
1. [How to deploy Scalar Admin for Kubernetes](https://scalardb.scalar-labs.com/docs/latest/helm-charts/how-to-deploy-scalar-admin-for-kubernetes/)
```

2024-03-12 03:24 UTC, josh-wong commented on README.md
> +You can use Helm Chart to deploy Scalar Admin for Kubernetes in the Kubernetes environment. See [Configure a custom values file for ScalarDB Cluster](https://scalardb.scalar-labs.com/docs/latest/helm
Thank you for the explanation! That makes sense to me😄

2024-03-12 03:28 UTC, josh-wong commented on README.md
> +You can use Helm Chart to deploy Scalar Admin for Kubernetes in the Kubernetes environment. See [Configure a custom values file for ScalarDB Cluster](https://scalardb.scalar-labs.com/docs/latest/helm
Actually, should we point to both the ScalarDB and ScalarDL docs sites in this case?

```suggestion
For details on how to use a Helm Chart to deploy Scalar Admin for Kubernetes in a Kubernetes environment, see the following documentation based on the product you're using:

### ScalarDB

1. [Configure a custom values file for Scalar Admin for Kubernetes](https://scalardb.scalar-labs.com/docs/latest/helm-charts/configure-custom-values-scalar-admin-for-kubernetes/)
1. [How to deploy Scalar Admin for Kubernetes](https://scalardb.scalar-labs.com/docs/latest/helm-charts/how-to-deploy-scalar-admin-for-kubernetes/)

### ScalarDL

1. [Configure a custom values file for Scalar Admin for Kubernetes](https://scalardl.scalar-labs.com/docs/latest/helm-charts/configure-custom-values-scalar-admin-for-kubernetes/)
1. [How to deploy Scalar Admin for Kubernetes](https://scalardl.scalar-labs.com/docs/latest/helm-charts/how-to-deploy-scalar-admin-for-kubernetes/)
```

2024-03-12 04:25 UTC, kota2and3kan commented on README.md
> +You can use Helm Chart to deploy Scalar Admin for Kubernetes in the Kubernetes environment. See [Configure a custom values file for ScalarDB Cluster](https://scalardb.scalar-labs.com/docs/latest/helm
> Actually, should we point to both the ScalarDB and ScalarDL docs sites in this case?

Ah, I see. The contents are the same, but the URLs are different.
Thank you for your suggestion!

2024-03-12 04:59 UTC, josh-wong approved these changes
LGTM! Thank you!🙇‍♂️

2024-03-12 07:47 UTC, supl approved these changes
LGTM.
Thank you 🙇

2024-03-14 03:22 UTC, feeblefakie approved these changes
LGTM! Thank you!

2024-03-14 03:22 UTC, merged